export const LOAD_DATA_FOR_ADD_CLIENT_PAGE = 'LOAD_DATA_FOR_ADD_CLIENT_PAGE';
export const LOAD_DATA_FOR_ADD_CLIENT_PAGE_SUCCESS = 'LOAD_DATA_FOR_ADD_CLIENT_PAGE_SUCCESS';

export const ADD_CLIENT_ON_CRM = 'ADD_CLIENT_ON_CRM';
export const ADD_CLIENT_ON_CRM_SUCCESS = 'ADD_CLIENT_ON_CRM_SUCCESS';
export const ADD_CLIENT_ON_CRM_FAILURE = 'ADD_CLIENT_ON_CRM_FAILURE';
