export const LOAD_GENERAL_PAGE_DATA = 'LOAD_GENERAL_PAGE_DATA';
export const LOAD_GENERAL_PAGE_DATA_SUCCESS = 'LOAD_GENERAL_PAGE_DATA_SUCCESS';
export const LOAD_GENERAL_PAGE_DATA_FAILURE = 'LOAD_GENERAL_PAGE_DATA_FAILURE';

export const ADD_CLIENT_IN_TRAIN = 'ADD_CLIENT_IN_TRAIN';

export const SEARCH_CLIENTS = 'SEARCH_CLIENTS';

export const CHANGE_TRAINER_FOR_GROUP = 'CHANGE_TRAINER_FOR_GROUP';
// export const LOAD_GENERAL_PAGE_DATA_FAILURE = 'LOAD_GENERAL_PAGE_DATA_FAILURE';

export const REMOVE_CLIENT_FROM_TRAIN = 'REMOVE_CLIENT_FROM_TRAIN';