export const LOAD_DATA_FOR_CREATE_AND_EDIT_PAGE = 'LOAD_DATA_FOR_CREATE_AND_EDIT_PAGE';
export const LOAD_DATA_FOR_CREATE_AND_EDIT_PAGE_SUCCESS = 'LOAD_DATA_FOR_CREATE_AND_EDIT_PAGE_SUCCESS';
export const LOAD_DATA_FOR_CREATE_AND_EDIT_PAGE_FAILURE = 'LOAD_DATA_FOR_CREATE_AND_EDIT_PAGE_FAILURE';


export const LOAD_GROUP_FOR_EDIT = 'LOAD_GROUP_FOR_EDIT';
export const LOAD_GROUP_FOR_EDIT_SUCCESS = 'LOAD_GROUP_FOR_EDIT_SUCCESS';
export const LOAD_GROUP_FOR_EDIT_FAILURE = 'LOAD_GROUP_FOR_EDIT_FAILURE';