export const LOAD_PROFILE_USER = 'LOAD_PROFILE_USER';
export const LOAD_PROFILE_USER_SUCCESS = 'LOAD_PROFILE_USER_SUCCESS';
export const LOAD_PROFILE_USER_FAILURE = 'LOAD_PROFILE_USER_FAILURE';

export const OPEN_EDIT_PAGE = 'OPEN_EDIT_PAGE';

export const EDIT_PROFILE = 'EDIT_PROFILE';
export const EDIT_PROFILE_SUCCESS = 'EDIT_PROFILE_SUCCESS';
export const EDIT_PROFILE_FAILURE = 'EDIT_PROFILE_FAILURE';

export const EDIT_PROFILE_PARENTS = 'EDIT_PROFILE_PARENTS';
export const CREATE_PROFILE_PARENTS = 'CREATE_PROFILE_PARENTS';
export const REMOVE_PROFILE_PARENTS = 'REMOVE_PROFILE_PARENTS';

export const BUY_ABONEMENT = 'BUY_ABONEMENT';
export const BUY_ABONEMENT_SUCCESS = 'BUY_ABONEMENT_SUCCESS';

export const LOAD_PROFILE_TYPE_ABONIMENT = 'LOAD_PROFILE_TYPE_ABONIMENT';
export const LOAD_PROFILE_STATUS = 'LOAD_PROFILE_STATUS';
export const LOAD_PROFILE_GROUP = 'LOAD_PROFILE_GROUP';
export const LOAD_PROFILE_COUCH = 'LOAD_PROFILE_COUCH';
export const LOAD_PROFILE_FILIAL = 'LOAD_PROFILE_FILIAL';
export const CLEAR_PROFILE = 'CLEAR_PROFILE';
export const CHANGE_PROFILE = 'CHANGE_PROFILE';
export const FILTERED_CLIENTS_FIO = 'FILTERED_CLIENTS_FIO';
export const UPDATE_PROFILE_CLUB_CARD = 'UPDATE_PROFILE_CLUB_CARD';