export const LOAD_DATA_SETTINGS_GROUP = 'LOAD_DATA_SETTINGS_GROUP';
export const LOAD_DATA_SETTINGS_GROUP_SUCCESS = 'LOAD_DATA_SETTINGS_GROUP_SUCCESS';
export const LOAD_DATA_SETTINGS_GROUP_FAILURE = 'LOAD_DATA_SETTINGS_GROUP_FAILURE';

export const FETCH_NEW_AGE_GROUP = 'FETCH_NEW_AGE_GROUP';
export const FETCH_GROUP = 'FETCH_GROUP';