export const START_LOAD_DATA_SETTINGS_ABONEMENT = 'START_LOAD_DATA_SETTINGS_ABONEMENT';
export const START_LOAD_DATA_SETTINGS_ABONEMENT_SUCCESS = 'START_LOAD_DATA_SETTINGS_ABONEMENT_SUCCESS';
export const START_LOAD_DATA_SETTINGS_ABONEMENT_FAILURE = 'START_LOAD_DATA_SETTINGS_ABONEMENT_FAILURE';

export const START_LOAD_DATA_ABONEMENT = 'START_LOAD_DATA_ABONEMENT';
export const START_LOAD_DATA_ABONEMENT_SUCCESS = 'START_LOAD_DATA_ABONEMENT_SUCCESS';
export const START_LOAD_DATA_ABONEMENT_FAILURE = 'START_LOAD_DATA_ABONEMENT_FAILURE';

export const UPLOAD_DATA_SETTINGS_ABONEMENT = 'UPLOAD_DATA_SETTINGS_ABONEMENT';

export const CLEAR_CURRENT_ABONEMENT = 'CLEAR_CURRENT_ABONEMENT';

export const REMOVE_ABONEMENT = 'REMOVE_ABONEMENT';
